using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Dt.VisualBehaviour;
using UnityEditor;

public class NodeMenuCreator: EditorWindow
{
    private const string Directory = "Assets/Editor/VisualBehaviour";
    private const string FileName = "VisualBehaviourMenu.cs";

    [MenuItem("Tool/Visual Behaviour/Rebuild Visual Behaviour Menu")]
    private static void GenerateMenu()
    {
        Assembly[] assemblies = AppDomain.CurrentDomain.GetAssemblies();

        List<Type> nodeScripts = assemblies
            .SelectMany(assembly => assembly.GetTypes())
            .Where(type =>
                typeof(VisualNode).IsAssignableFrom(type) &&
                !type.IsInterface &&
                !type.IsAbstract
            )
            .ToList();

        WriteScript(nodeScripts);
    }

    private static void WriteScript(List<Type> nodes)
    {
        StringBuilder sb = new StringBuilder();
        sb.AppendLine("// This file is automatically generated.");
        sb.AppendLine("using UnityEditor;");
        sb.AppendLine();
        sb.AppendLine("namespace Dt.VisualBehaviour.Editor");
        sb.AppendLine("{");
        sb.AppendLine("public static class BehaviourTreeMenu");
        sb.AppendLine("{");
        foreach (Type script in nodes)
        {
            string subDir = "Node";
            if (script.IsSubclassOf(typeof(ControllerNode)))
            {
                subDir = "Controller";
            }
            sb.AppendLine(
                $"[MenuItem(\"GameObject/Visual Behaviour/{subDir}/{script.Name}\", false, -10000)]");
            sb.AppendLine($"private static void Create{script.Name}(MenuCommand menuCommand)");
            sb.AppendLine("{");
            sb.AppendLine(
                $"NodeHierarchyCreator.Create(menuCommand, \"{script.FullName}\", \"{script.Assembly.GetName()}\");");
            sb.AppendLine("}");
        }

        sb.AppendLine("}");
        sb.AppendLine("}");
        if (!System.IO.Directory.Exists(Directory))
        {
            System.IO.Directory.CreateDirectory(Directory);
        }
        File.WriteAllText(Directory + "/" + FileName, sb.ToString());
        AssetDatabase.ImportAsset(Directory + "/" + FileName, ImportAssetOptions.ForceUpdate);
    }
}